spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinco
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: false
custom:
  jwt:
    secret: "aVeryLongSecretKey_ChangeMe_2025!"
    accessExpireSeconds: 1800
    refreshExpireSeconds: 86400
